// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eibrahimarisoy/car_rental/internal/location (interfaces: LocationServiceInterface)

// Package location is a generated GoMock package.
package location

import (
	reflect "reflect"

	models "github.com/eibrahimarisoy/car_rental/internal/models"
	pagination "github.com/eibrahimarisoy/car_rental/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockLocationServiceInterface is a mock of LocationServiceInterface interface.
type MockLocationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLocationServiceInterfaceMockRecorder
}

// MockLocationServiceInterfaceMockRecorder is the mock recorder for MockLocationServiceInterface.
type MockLocationServiceInterfaceMockRecorder struct {
	mock *MockLocationServiceInterface
}

// NewMockLocationServiceInterface creates a new mock instance.
func NewMockLocationServiceInterface(ctrl *gomock.Controller) *MockLocationServiceInterface {
	mock := &MockLocationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockLocationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationServiceInterface) EXPECT() *MockLocationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateLocation mocks base method.
func (m *MockLocationServiceInterface) CreateLocation(arg0 *models.Location) (*models.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", arg0)
	ret0, _ := ret[0].(*models.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MockLocationServiceInterfaceMockRecorder) CreateLocation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MockLocationServiceInterface)(nil).CreateLocation), arg0)
}

// GetAllActiveLocations mocks base method.
func (m *MockLocationServiceInterface) GetAllActiveLocations(arg0 *pagination.Pagination) (*[]models.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActiveLocations", arg0)
	ret0, _ := ret[0].(*[]models.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActiveLocations indicates an expected call of GetAllActiveLocations.
func (mr *MockLocationServiceInterfaceMockRecorder) GetAllActiveLocations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActiveLocations", reflect.TypeOf((*MockLocationServiceInterface)(nil).GetAllActiveLocations), arg0)
}
