ServerConfig:
  AppVersion: 1.0.0
  Mode: Development
  RoutePrefix: /api/v1
  Debug: true
  Port: 8080
  TimeoutSecs: 60
  ReadTimeoutSecs: 60
  WriteTimeoutSecs: 12

DBConfig:
  DataSourceName: postgres://emre:Django123.@postgresdb:5432/car_rental?sslmode=disable
  MaxOpen: 50
  MaxIdle: 50
  MaxLifetime: 5
  DB_USER: emre
  DB_PASSWORD: Django123.
  DB_HOST: postgresdb 
  DB_PORT: 5432 
  DB_NAME: car_rental

LoggerConfig:
  Development: true
  Encoding: JSON
  Level: debug