basePath: /api/v1
definitions:
  _type.APIErrorResponse:
    properties:
      errCode:
        type: integer
      errDetails: {}
      errMessage:
        type: string
    type: object
  car.CarRequest:
    properties:
      fuel:
        type: string
      name:
        type: string
      office_id:
        type: string
      transmission:
        type: string
      vendor_id:
        type: string
    type: object
  car.CarResponse:
    properties:
      fuel:
        type: string
      id:
        type: string
      name:
        type: string
      office:
        $ref: '#/definitions/office.OfficeResponse'
      transmission:
        type: string
      vendor:
        $ref: '#/definitions/vendors.VendorResponse'
    type: object
  location.LocationRequest:
    properties:
      is_active:
        type: boolean
      name:
        type: string
    type: object
  location.LocationResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      updated_at:
        type: string
    type: object
  office.OfficeRequest:
    properties:
      closing_hours:
        type: string
      location_id:
        type: string
      opening_hours:
        type: string
      vendor_id:
        type: string
      working_days:
        items:
          type: integer
        type: array
    type: object
  office.OfficeResponse:
    properties:
      closing_hours:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/location.LocationResponse'
      location_id:
        type: string
      opening_hours:
        type: string
      vendor:
        $ref: '#/definitions/vendors.VendorResponse'
      vendor_id:
        type: string
      working_days:
        items:
          type: string
        type: array
    type: object
  pagination.Pagination:
    properties:
      limit:
        type: integer
      page:
        type: integer
      q:
        type: string
      rows: {}
      total_pages:
        type: integer
      total_rows:
        type: integer
    type: object
  vendors.VendorRequest:
    properties:
      name:
        type: string
    type: object
  vendors.VendorResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: eibrahimarisoy@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Car Rental API implementation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Car Rental API
  version: "1.0"
paths:
  /cars/:
    get:
      consumes:
      - application/json
      description: List all cars with pagination and search
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.Pagination'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: List all cars
      tags:
      - car
    post:
      consumes:
      - application/json
      description: Create a car with payload
      parameters:
      - description: Car payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/car.CarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/car.CarResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: Create a car
      tags:
      - car
  /locations/:
    get:
      consumes:
      - application/json
      description: List all locations with pagination and search
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.Pagination'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: List all locations
      tags:
      - location
    post:
      consumes:
      - application/json
      description: Create a location with payload
      parameters:
      - description: Location payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/location.LocationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/location.LocationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: Create a location
      tags:
      - location
  /offices/:
    get:
      consumes:
      - application/json
      description: List all offices with pagination and search
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.Pagination'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: List all offices
      tags:
      - offices
    post:
      consumes:
      - application/json
      description: Create a office with payload
      parameters:
      - description: Office payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/office.OfficeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/office.OfficeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: Create a office
      tags:
      - offices
  /vendors/:
    get:
      consumes:
      - application/json
      description: List all vendors with pagination and search
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.Pagination'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: List all vendors
      tags:
      - vendors
    post:
      consumes:
      - application/json
      description: Create a vendor with payload
      parameters:
      - description: Vendor payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vendors.VendorRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/vendors.VendorResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: Create a vendor
      tags:
      - vendors
swagger: "2.0"
