basePath: /api/v1
definitions:
  _type.APIErrorResponse:
    properties:
      errCode:
        type: integer
      errDetails: {}
      errMessage:
        type: string
    type: object
  location.LocationRequest:
    properties:
      is_active:
        type: boolean
      name:
        type: string
    type: object
  pagination.Pagination:
    properties:
      limit:
        type: integer
      page:
        type: integer
      q:
        type: string
      rows: {}
      total_pages:
        type: integer
      total_rows:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: eibrahimarisoy@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Car Rental API implementation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Car Rental API
  version: "1.0"
paths:
  /locations/:
    get:
      consumes:
      - application/json
      description: List all locations with pagination and search
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.Pagination'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: List all locations
      tags:
      - location
    post:
      consumes:
      - application/json
      description: Create a location with payload
      parameters:
      - description: Location payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/location.LocationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.Pagination'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/_type.APIErrorResponse'
      summary: Create a location
      tags:
      - location
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
